version: "3.9"

services:
  simple-orm:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sqlite3
    volumes:
      - ./data:/data
      - ./db/:/sqlite_db/

  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./db/:/root/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped

volumes:
  sqlite3:
